name: tweet_automation
description: This is a tweet automation app
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get_it: ^7.2.0
  twitter_api_v2: ^4.3.3

dev_dependencies:
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
  generate: true
